### PR TITLE
password-store: add option for fish completion.

### PR DESCRIPTION
**Pull request by judu**
I'm having a go at fish for the next few weeks. So I need completion :grin: 

(I may make a fish-completion exlib at some point if I decide to stick with this shell.)

### CODE REVIEW

**Comment by judu** [comment]
Wait, it does not work as expected.

**Comment by Kdecherf** [comment]
Hey @judu,

Just merged a bump to 1.7.3, you should rebase ;-)

**Comment by judu** [comment]
Done :)

**Comment by Kdecherf** [comment]
LGTM :+1: Thanks

**Pull request merged**
